# Site settings
author: E.C.
title: Coding Curve
header-img: img/home-bg.png
email: caprice@mail.usf.edu
copyright_name: E.C.
description: > # this means to ignore newlines until "baseurl:"
  A Web Developer Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  EdselCaprice

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
